spring:
  datasource:
    url: jdbc:h2:mem:E_COMMERCE
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 9000